// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmlibeiyvycnvhngxtxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbGliZWl5dnljbnZobmd4dHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5Nzg0NjYsImV4cCI6MjA5MTU1NDQ2Nn0.IPLXbWUC-EnIlKw2kpEsY4SErUT8GTS3gFFfOqTDEcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});